version: '3'

services:
  ui:
    build:
      dockerfile: Dockerfile.prod
      context: ./ui
    container_name: reg-sport-ui
    restart: unless-stopped
    command: serve -s dist -l 3000
    networks:
      - reg-sport-network
  landing:
    build:
      dockerfile: Dockerfile.prod
      context: ./landing
    container_name: reg-sport-landing
    restart: unless-stopped
    command: serve dist -l 3000
    networks:
      - reg-sport-network
  api:
    build:
      dockerfile: Dockerfile.prod
      context: ./api
    container_name: reg-sport-api
    command: npm run start:prod
    restart: unless-stopped
    environment:
      - PORT=3001
      - POSTGRES_HOST=api_db
      - POSTGRES_USER=busyl
      - POSTGRES_PASSWORD=aszrqs123cgfsasas
      - POSTGRES_DB=pgdb
      - POSTGRES_PORT=5432
    depends_on:
      - api_db
    networks:
      - reg-sport-network

  api_db:
    image: postgres:14.1-alpine
    container_name: reg-sport-api-db
    restart: unless-stopped
    volumes:
      - postgres_api:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: busyl
      POSTGRES_PASSWORD: aszrqs123cgfsasas
      POSTGRES_DB: pgdb
    networks:
      - reg-sport-network

  nginx:
    image: nginx:stable-alpine
    container_name: reg-sport-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - ui
      - api
      - landing
    networks:
      - reg-sport-network

  test_pg_db:
    image: postgres:15.2-alpine
    container_name: reg-sport-test_pg_db
    restart: unless-stopped
    volumes:
      - postgres_api:/var/lib/postgresql
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: busyl
      POSTGRES_PASSWORD: aszrqs123cgfsasas
      POSTGRES_DB: pgdb

  mongo:
    image: mongo:6.0-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: busyl
      MONGO_INITDB_ROOT_PASSWORD: aszrc

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "38081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: busyl
      ME_CONFIG_MONGODB_ADMINPASSWORD: aszrc
      ME_CONFIG_MONGODB_URL: mongodb://busyl:example@mongo:27017/

volumes:
  postgres_api:

networks:
  reg-sport-network:
    driver: bridge
